CREATE TABLE DC_REGISTER.CP_HS_ENT_SUP_FOR(
 GID VARCHAR(36),
 PRIPID VARCHAR(36),
 ECOTECDEVZONE VARCHAR(5),
 PROTYPE VARCHAR(2),
 CONGRO NUMERIC(18,6),
 CONGROCUR VARCHAR(3),
 CONGROUSD NUMERIC(18,6),
 REGCAPCUR VARCHAR(3),
 RECCAPCUR VARCHAR(3),
 REGCAPUSD NUMERIC(18,6),
 REGCAPRMB NUMERIC(18,6),
 RECCAPUSD NUMERIC(18,6),
 RECCAPRMB NUMERIC(18,6),
 DOMEREGCAP NUMERIC(18,6),
 DOMEREGCAPCUR VARCHAR(3),
 DOMEREGCAPUSD NUMERIC(18,6),
 DOMEREGCAPINVPROP NUMERIC(7,4),
 DOMERECCAP NUMERIC(18,6),
 DOMERECCAPCUR VARCHAR(3),
 DOMERECCAPUSD NUMERIC(18,6),
 DOMERECCAPCONPROP NUMERIC(7,4),
 FORREGCAP NUMERIC(18,6),
 FORREGCAPCUR VARCHAR(3),
 FORREGCAPUSD NUMERIC(18,6),
 FORRECCAPCONPROP NUMERIC(7,4),
 CHAMECDATE DATETIME,
 EXAAUTH VARCHAR(100),
 SANDOCNO VARCHAR(50),
 SANDATE DATETIME,
 FORENTNAME VARCHAR(100),
 OPEACTTYPE VARCHAR(2),
 ITEMOFOPORCPRO VARCHAR(512),
 CONOFCONTRPRO VARCHAR(512),
 FORDON VARCHAR(100),
 FORREGECAP NUMERIC(18,6),
 FOROPSCOPE VARCHAR(1000),
 MIDPREINDCODE VARCHAR(64),
 FORCAPINDCODE VARCHAR(64),
 FORENTFORNAME VARCHAR(200),
 FORENTOPFROM DATETIME,
 FORENTOPTO DATETIME,
 FORENTAUTSIGN VARCHAR(100),
 FORENLIAFOR VARCHAR(200),
 FORENTCAPCUR VARCHAR(64),
 SANOPFROM DATETIME,
 SANOPTO DATETIME,
 USDEXCHANGERATE NUMERIC(18,6),
 TIMESTAMP DATETIME,
 S_EXT_FROMNODE VARCHAR(6),
 S_EXTDATATIME TIMESTAMP,
 PRIMARY KEY (GID)
);
COMMENT ON TABLE DC_REGISTER.CP_HS_ENT_SUP_FOR IS '外资补充信息历史表';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.PRIPID IS '业务流水号';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.PRIPID IS '主体身份代码';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.ECOTECDEVZONE IS '住所所在经济开发区';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.PROTYPE IS '项目类型';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.CONGRO IS '投资总额';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.CONGROCUR IS '投资总额币种';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.CONGROUSD IS '投资总额折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.REGCAPCUR IS '注册资本(金)币种';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.RECCAPCUR IS '实收资本币种';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.REGCAPUSD IS '注册资本(金)折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.REGCAPRMB IS '注册资本(金)折人民币';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.RECCAPUSD IS '实收资本折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.RECCAPRMB IS '实收资本折人民币';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.DOMEREGCAP IS '中方注册资本(金)';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.DOMEREGCAPCUR IS '中方注册资本(金)币种';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.DOMEREGCAPUSD IS '中方注册资本(金)折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.DOMEREGCAPINVPROP IS '中方注册资本(金)出资比例';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.DOMERECCAP IS '中方实收资本';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.DOMERECCAPCUR IS '中方实收资本币种';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.DOMERECCAPUSD IS '中方实收资本折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.DOMERECCAPCONPROP IS '中方实收资本出资比例';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORREGCAP IS '外方注册资本(金)';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORREGCAPCUR IS '外方注册资本(金)币种';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORREGCAPUSD IS '外方注册资本(金)折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORREGCAPINVPROP IS '外方注册资本(金)出资比例';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORRECCAP IS '外方实收资本';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORRECCAPCUR IS '外方实收资本币种';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORRECCAPUSD IS '外方实收资本折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORRECCAPCONPROP IS '外方实收资本出资比例';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.CHAMECDATE IS '转型日期';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.EXAAUTH IS '审批机关';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.SANDOCNO IS '批准文号';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.SANDATE IS '批准日期';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORENTNAME IS '外国(地区)企业名称';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.OPEACTTYPE IS '经营活动类型';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.ITEMOFOPORCPRO IS '承包工程或经营管理项目';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.CONOFCONTRPRO IS '承包工程或经营管理内容';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORDOM IS '境外住所';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORREGECAP IS '境外注册资本';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FOROPSCOPE IS '境外经营范围';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.MIDPREINDCODE IS '中西部优势产业代码';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORCAPINDCODE IS '外资产业代码';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORENTFORNAME IS '外国(地区)企业外文名称';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORENTOPFROM IS '外国(地区)企业经营起始日期';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORENTOPTO IS '外国(地区)企业经营截止日期';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORENTAUTSIGN IS '外国(地区)企业有权签字人';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORENLIAFOR IS '外国(地区)企业责任形式';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.FORENTCAPCUR IS '外国(地区)企业资本(资产)币种';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.SANOPFROM IS '批准驻在期限自';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.SANOPTO IS '批准驻在期限至';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.USDEXCHANGERATE IS '美元汇率';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.TIMESTAMP IS '时间戳';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.S_EXT_FROMNODE IS '数据上报单位';
COMMENT ON COLUMN DC_REGISTER.CP_HS_ENT_SUP_FOR.S_EXT_DATATIME IS '数据上报时间';