CREATE TABLE DC_REGISTER.CP_RS_INVESTOR(
	INVID VARCHAR(36),
	PRIPID VARCHAR(36),
	INV VARCHAR(100),
	INVTYPE VARCHAR(2),
	CERTYPE VARCHAR(2),
	CERNO VARCHAR(40),
	BLICTYPE VARCHAR(2),
	BLICNO VARCHAR(26),
	CURRENCY VARCHAR(3),
	SUBCONAM NUMERIC(18,6),
	ACCONAM NUMERIC(18,6),
	SUBCONAMUSD NUMERIC(18,6),
	CURACTCONAMUSD NUMERIC(18,6),
	DOM VARCHAR(200),
	COUNTRY VARCHAR(10),
	EXEAFFSIGN CHAR(1),
	POSTALCODE VARCHAR(6),
	TEL VARCHAR(30),
	SEX CHAR(1),
	NATDATE DATETIME,
	LITEDEG VARCHAR(30),
	POLSTAND VARCHAR(36),
	NATION VARCHAR(10),
	SUBCONFORM VARCHAR(200),
	SUBCONPROP NUMERIC(18,6),
	CONDATE DATETIME,
	RESPFORM VARCHAR(64),
	SCONFORM VARCHAR(200),
	OCCST VARCHAR(128),
	DOMPROV VARCHAR(36),
	DOMCITY VARCHAR(10),
	DOMCOUNTY VARCHAR(36),
	DOMOTHER VARCHAR(100),
	INITIATORSIGN VARCHAR(3),
	LOCALSIGN VARCHAR(1),
	PARTNERNATURE VARCHAR(1),
	MOBTEL VARCHAR(30),
	EMAIL VARCHAR(100),
	ENTLEREP VARCHAR(100),
	TIMESTAMP DATETIME,
 	S_EXT_FROMNODE VARCHAR(6),
 	S_EXTDATATIME TIMESTAMP,
 	PRIMARY KEY (INVID)
);
COMMENT ON TABLE DC_REGISTER.CP_RS_INVESTOR IS '投资人信息';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.INVID IS '投资人身份标识';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.PRIPID IS '主体身份代码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.INV IS '投资人';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.INVTYPE IS '投资人类型';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.CERTYPE IS '证件类型';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.CERNO IS '证件号码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.BLICTYPE IS '证照类型';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.BLICNO IS '证照编号';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.CURRENCY IS '币种';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.SUBCONAM IS '认缴出资额';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.ACCONAM IS '实缴出资额';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.SUBCONAMUSD IS '认缴出资额折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.CURACTCONAMUSD IS '实缴出资额折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.DOM IS '住所';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.COUNTRY IS '国别(地区)';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.EXEAFFSIGN IS '执行合伙事务标志';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.POSTALCODE IS '邮政编码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.TEL IS '联系电话';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.SEX IS '性别';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.NATDATE IS '出生日期';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.LITEDEG IS '文化程度';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.POLSTAND IS '政治面貌';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.NATION IS '民族';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.SUBCONFORM IS '认缴出资方式';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.SUBCONPROP IS '认缴出资比例';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.CONDATE IS '认缴出资期限';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.RESPFORM IS '承担责任方式/责任形式';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.SCONFORM IS '出资方式';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.OCCST IS '职业状况';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.DOMPROV IS '地址省';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.DOMCITY IS '地址市';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.DOMCOUNTY IS '地址县';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.DOMOTHER IS '地址其他';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.INITIATORSIGN IS '发起人标识';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.LOCALSIGN IS '中外方标识';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.PARTNERNATURE IS '合伙人性质';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.MOBTEL IS '移动电话';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.EMAIL IS '电子邮箱';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.ENTLEREP IS '法定代表人';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.TIMESTAMP IS '时间戳';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.S_EXT_FROMNODE IS '数据上报单位';
COMMENT ON COLUMN DC_REGISTER.CP_RS_INVESTOR.S_EXT_DATATIME IS '数据上报时间';
