CREATE TABLE DC_REGISTER.CP_RS_ASSIGNEDRPT(
	DRPTID VARCHAR(50),
	PRIPID VARCHAR(36),
	INVID VARCHAR(100),
	NAME VARCHAR(200),
	SEX VARCHAR(64),
	ACCDSIDE VARCHAR(100),
	CERTYPE VARCHAR(2),
	ERNO VARCHAR(50),
	COUNTRY VARCHAR(128),
	NATION VARCHAR(64),
	NATDATE DATETIME,
	HOUSEADD VARCHAR(600),
	TEL VARCHAR(30),
	MOBTEL VARCHAR(30),
	EMAIL VARCHAR(100),
	TIMESTAMP DATETIME,
	S_EXT_FROMNODE VARCHAR(6),
	S_EXT_DATATIME TIMESTAMP,
	PRIMARY KEY (DRPTID)
);

COMMENT ON TABLE DC_REGISTER.CP_RS_ASSIGNEDRPT IS '委派代表信息';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.DRPTID IS '委派代表ID';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.PRIPID IS '主体身份代码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.INVID IS '合伙人ID';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.NAME IS '姓名';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.SEX IS '性别';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.ACCDSIDE IS '委派方';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.CERTYPE IS '证件类型';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.CERNO IS '证件号码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.COUNTRY IS '国籍';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.NATION IS '民族';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.NATDATE IS '出生日期';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.HOUSEADD IS '住址';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.TEL IS '联系电话';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.MOBTEL IS '移动电话';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.EMAIL IS '电子邮箱';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.TIMESTAMP IS '时间戳';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.S_EXT_FROMNODE IS '数据上报单位';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ASSIGNEDRPT.S_EXT_DATATIME IS '数据上报时间';
