CREATE TABLE DC_REGISTER.CP_RS_ENT(
	PRIPID VARCHAR(36),
	ENTNAME VARCHAR(400),
	REGNO varchar(30),
	ENTTYPE varchar(4),
	REGCAP numeric(18,6),
	INDUSTRYPHY varchar(1),
	INDUSTRYCO varchar(4),
	ESTDATE datetime,
	OPSCOTYPE varchar(2),
	OPSCOPE varchar(3000),
	OPFROM datetime,
	OPTO datetime,
	LOCALADM varchar(9),
	REGORG varchar(9),
	OPSTATE varchar(2),
	DOM varchar(200),
	DOMDISTRICT varchar(6),
	RECCAP numeric(18,6),
	INSFORM varchar(2),
	CANREA varchar(10),
	CANDATE datetime,
	APPRDATE datetime,
	UNISCID varchar(18),
	COUNTRY varchar(3),
	NAMEID varchar(36),
	DOMPROV varchar(10),
	DOMCITY varchar(10),
	DOMCOUNTY varchar(10),
	DOMOTHER varchar(100),
	ISBOARD varchar(1),
	ISSUPED varchar(1),
	SSMJGFFLAG varchar(2),
	AICID varchar(9),
	FILEID varchar(40),
	REVDATE datetime,
	REMARKS varchar(200),
	GROUPPARENTFLAG varchar(1),
	GRPNAME varchar(400),
	GRPSHFORM varchar(400),
	GROUPSONFLAG varchar(1),
	COUNTRYAPPROVENAMEFLAG VARCHAR(1),
	LEREPNAME varchar(2000),
	LEREPCERTTYPE varchar(200),
	LEREPCERNO varchar(2000),
	TIMESTAMP datetime,
	S_EXT_FROMNODE VARCHAR(6),
	S_EXT_DATATIME TIMESTAMP,
	PRIMARY KEY (PRIPID)
);


COMMENT ON TABLE DC_REGISTER.CP_RS_ENT IS '企业基本信息';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.PRIPID IS '主体身份代码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.ENTNAME IS '企业(机构)名称';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.REGNO IS '注册号';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.ENTTYPE IS '经营主体类型';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.REGCAP IS '注册资本(金)';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.INDUSTRYPHY IS '行业门类';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.INDUSTRYCO IS '行业代码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.ESTDATE IS '成立日期';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.OPSCOTYPE IS '业务范围类型';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.OPSCOPE IS '经营(业务)范围';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.OPFROM IS '经营(驻在)期限自';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.OPTO IS '经营(驻在)期限至';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.LOCALADM IS '属地管辖机关';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.REGORG IS '登记管辖机关';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.OPSTATE IS '经营状态';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.DOM IS '住所';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.DOMDISTRICT IS '住所所在行政区划';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.RECCAP IS '实收资本';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.INSFORM IS '设立方式';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.CANREA IS '注销原因';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.CANDATE IS '注销日期';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.APPRDATE IS '核准日期';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.UNISCID IS '统一社会信用代码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.COUNTRY IS '国别(地区)';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.NAMEID IS '名称结果ID';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.DOMPROV IS '住所（省）';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.DOMCITY IS '住所（市）';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.DOMCOUNTY IS '住所（区县）';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.DOMOTHER IS '住所其他';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.ISBOARD IS '是否设立董事会';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.ISSUPED IS '是否设立监事会';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.SSMJGFFLAG IS '是否是股份有限公司（上市）及募集设立的股份有限公司';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.AICID IS '登记机关';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.FILEID IS '档案编号';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.REVDATE IS '吊销日期';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.REMARKS IS '备注';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.GROUPPARENTFLAG IS '是否集团母公司';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.GRPNAME IS '集团名称';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.GRPSHFORM IS '集团简称';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.GROUPSONFLAG IS '是否集团子公司';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.COUNTRYAPPROVENAMEFLAG IS '是否国家核准名称';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.LEREPNAME IS '法定代表人';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.LEREPCERTTYPE IS '法定代表人证件类型';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.LEREPCERNO IS '法定代表人证件号码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.TIMESTAMP IS '时间戳';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.S_EXT_FROMNODE IS '数据上报单位';
COMMENT ON COLUMN DC_REGISTER.CP_RS_ENT.S_EXT_DATATIME IS '数据上报时间';


