CREATE TABLE DC_REGISTER.CP_RS_STAGESPAY(
	PAID VARCHAR(50),
	INVID VARCHAR(36),
	CURSUBCONAM NUMERIC(18,6),
	CURACTCONAM NUMERIC(18,6),
	CONFORM CHAR(1),
	CONDATE DATETIME,
	CURACTCONAMUSD NUMERIC(18,6),
	CURRENCY VARCHAR(3),
	CONSOURCE CHAR(1),
	POSDUEREA VARCHAR(1000),
	VERCAPORG VARCHAR(100),
	CONTO DATETIME,
	PRIPID VARCHAR(36),
	CONFLAG VARCHAR(1),
	TIMESTAMP DATETIME,
 	S_EXT_FROMNODE VARCHAR(6),
 	S_EXTDATATIME TIMESTAMP,
 	PRIMARY KEY (PAID)
);
COMMENT ON TABLE DC_REGISTER.CP_RS_STAGESPAY IS '投资人分期出资信息';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.PAID IS '分期出资ID';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.INVID IS '投资人身份标识';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CURSUBCONAM IS '本期认缴出资额';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CURACTCONAMDAD IS '本期实缴出资额';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CONFORM IS '出资方式';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CONDATE IS '出资日期';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CURACTCONAMUSD IS '本期实缴出资额折万美元';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CURRENCY IS '币种';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CONSOURCE IS '出资来源';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.POSDUEREA IS '欠资原因';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.VERCAPORG IS '验资(审计)机构';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CONTO IS '出资期限至';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.PRIPID IS '主体身份代码';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.CONFLAG IS '实缴认缴标识';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.TIMESTAMP IS '时间戳';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.S_EXT_FROMNODE IS '数据上报单位';
COMMENT ON COLUMN DC_REGISTER.CP_RS_STAGESPAY.S_EXT_DATATIME IS '数据上报时间';